### ISSUE TITLE
[Feature request] add ivp6 support, direct add to hosts file

### ISSUE THREAD

**Issue by ibay770** [idle-PB/Dnscope.io#6]
Thanks for the amazing software. If possible, try to add support for ipv6, unless it doesn't make a difference.
Also if possible, to add an option, to add the blocked domains to the hosts file, 
I'm trying to detrack all browsers so this is a big help. Many times, people don't want to use software bc of the tracking, this is invaluble in stopping that.

**Comment by idle-PB** [comment]
Thanks for the nice comment, IPv6 is on the to do list but I want to get it cross platform first, it only needs minor changes to make it work on OSX Linux and Raspberry PI.   

I don't think there's any benefit to add blocks to the Host File, My understanding of how Windows deals with its Host File is like some disaster waiting to happen and it's grossly inefficient. I'm pretty sure if you put the source of the block list into the Host files which is 75mb with ~3million domains windows would probably refuse to start up. The 3 million domains is also why the program is 4mb, 3.0mb is the block list in a bloom filter.  Your personal blocks and allows are stored in the cache and written out to file under users->appdata->roaming ->dnscope->dnsdata.bin you can simply build it to suit then copy it to another machine if you want.
